---
- hosts: all
  tasks:
    - name: set hostname
      hostname:
        name: nirvana

    - name: crete group with admin privileges
      group:
        name: "{{ admin_group }}"
        state: present

    - name: create functional user
      user:
        name: "{{ functional_user }}"
        comment: Functional_ID
        group: "{{ admin_group }}"
        shell: /bin/bash
        expires: -1
...