---
- name: include variables
  include_vars: "{{ item }}"
  with_first_found:
    - "../vars/vars.yml"

- name: change hostname to nirvana
  hostname:
    name: nirvana

- name: create group with admin privileges
  group:
    name: "{{ admin_group }}"
    state: present

- name: create functional user
  user:
    name: "{{ functional_user }}"
    comment: Functional_ID
    group: "{{ admin_group }}"
    shell: /bin/bash
    expires: -1
...